module Acapela
  module Voices
    PER_LANGUAGE = {
      :ar      =>  {:female=>["Leila", "Salma"], :male=>["Mehdi", "Nizar"]},
      :ca      =>  {:female=>["Laia"], :male=>[]},
      :cs      =>  {:female=>["Eliska"], :male=>[]},
      :da      =>  {:female=>["Mette"], :male=>["Rasmus"]},
      :de      =>  {:female=>["Julia", "Sarah"], :male=>["Andreas", "Klaus"]},
      :el      =>  {:female=>[], :male=>["Dimitris"]},
      :en      =>  {:female=>["Deepa", "Lucy", "QueenElizabeth", "Rachel", "Heather", "Laura", "Nelly", "Tracy"], :male=>["Graham", "Nizareng", "Peter", "Kenny", "Micah", "Ryan", "Saul"]},
      :en_GB   =>  {:female=>["Lucy", "QueenElizabeth", "Rachel"], :male=>["Graham", "Nizareng", "Peter"]},
      :en_IN   =>  {:female=>["Deepa"], :male=>[]},
      :en_US   =>  {:female=>["Heather", "Laura", "Nelly", "Tracy"], :male=>["Kenny", "Micah", "Ryan", "Saul"]},
      :es      =>  {:female=>["Ines", "Maria", "Rosa"], :male=>["Antonio"]},
      :es_ES   =>  {:female=>["Ines", "Maria"], :male=>["Antonio"]},
      :es_US   =>  {:female=>["Rosa"], :male=>[]},
      :fi      =>  {:female=>["Sanna"], :male=>[]},
      :fr      =>  {:female=>["Justine", "Louise", "Alice", "Claire", "Julie", "Margaux"], :male=>["Antoine", "Bruno"]},
      :fr_BE   =>  {:female=>["Justine"], :male=>[]},
      :fr_CA   =>  {:female=>["Louise"], :male=>[]},
      :fr_FR   =>  {:female=>["Alice", "Claire", "Julie", "Margaux"], :male=>["Antoine", "Bruno"]},
      :gb      =>  {:female=>[], :male=>["Kal"]},
      :it      =>  {:female=>["Chiara", "Fabiana", "chiara", "fabiana"], :male=>["Vittorio", "vittorio"]},
      :nl      =>  {:female=>["Sofie", "Zoe", "Femke", "Jasmijn"], :male=>["Jeroen", "Daan", "Max"]},
      :nl_BE   =>  {:female=>["Sofie", "Zoe"], :male=>["Jeroen"]},
      :nl_NL   =>  {:female=>["Femke", "Jasmijn"], :male=>["Daan", "Max"]},
      :no      =>  {:female=>["Bente", "Kari"], :male=>["Olav"]},
      :pl      =>  {:female=>["Ania"], :male=>[]},
      :pt      =>  {:female=>["Marcia", "Celia"], :male=>[]},
      :pt_BR   =>  {:female=>["Marcia"], :male=>[]},
      :pt_PT   =>  {:female=>["Celia"], :male=>[]},
      :ru      =>  {:female=>["Alyona"], :male=>[]},
      :sc      =>  {:female=>["Mia"], :male=>[]},
      :sv      =>  {:female=>["Elin", "Emma"], :male=>["Emil", "Erik", "Samuel"]},
      :sv_FI   =>  {:female=>[], :male=>["Samuel"]},
      :sv_SE   =>  {:female=>["Elin", "Emma"], :male=>["Emil", "Erik"]},
      :tr      =>  {:female=>["Ipek"], :male=>[]}
    }
  end
end
